services:
  - type: web
    name: topsis-web
    env: python
    plan: free
    buildCommand: pip install -r web/requirements.txt
    startCommand: streamlit run web/frontend/app.py --server.port $PORT --server.address 0.0.0.0
